"""
Tests for `pymerlin package`, focused on what ends up inside the JAR.

The real shim JAR is ~3 MB and irrelevant to these assertions, so each test packages
against a stand-in JAR holding just a manifest — `_package` copies entries verbatim
and only rewrites META-INF/MANIFEST.MF, so a one-entry stand-in exercises the same code.

Dependency detection itself is covered by test_requirements.py; what matters here is
which file wins and how it reaches the JAR.
"""

import inspect
import zipfile

import pytest

from pymerlin._internal import _cli
from pymerlin._internal._cli import _package


BASE_MANIFEST = b"Manifest-Version: 1.0\r\nCreated-By: test\r\n\r\n"

# Imports only pymerlin, which the worker image already provides — so nothing is
# generated unless a test adds an import of its own.
MODEL_SOURCE = """
from pymerlin import MissionModel


@MissionModel
class Mission:
    def __init__(self, registrar):
        pass
"""

MODEL_WITH_DEPENDENCY = MODEL_SOURCE + "\nimport yaml\n"


@pytest.fixture
def shim_jar(tmp_path, monkeypatch):
    jar = tmp_path / "pymerlin-shim.jar"
    with zipfile.ZipFile(jar, "w") as z:
        z.writestr("META-INF/MANIFEST.MF", BASE_MANIFEST)
        z.writestr("gov/nasa/ammos/aerie/pymerlin/shim/ShimModelType.class", b"\xca\xfe\xba\xbe")
    monkeypatch.setattr(_cli, "_SHIM_JAR", jar)
    return jar


@pytest.fixture
def model_file(tmp_path):
    model = tmp_path / "model.py"
    model.write_text(MODEL_SOURCE)
    return model


def manifest_of(jar_path):
    with zipfile.ZipFile(jar_path) as z:
        return z.read("META-INF/MANIFEST.MF").decode("utf-8")


def entries_of(jar_path):
    with zipfile.ZipFile(jar_path) as z:
        return z.namelist()


def requirements_in(jar_path):
    with zipfile.ZipFile(jar_path) as z:
        return z.read("pymerlin_requirements.txt").decode("utf-8")


# --- a requirements.txt on disk is never an input ---------------------------


def test_adjacent_requirements_file_is_ignored(tmp_path, shim_jar):
    # Generation is the only source. At a project root a requirements.txt is usually the
    # dev toolchain, and bundling it would install pytest and sphinx on the worker in
    # place of what the model actually imports.
    model = tmp_path / "model.py"
    model.write_text(MODEL_WITH_DEPENDENCY)
    (tmp_path / "requirements.txt").write_text("pytest\nsphinx\n")
    out = tmp_path / "out.jar"

    _package(f"{model}:Mission", str(out))

    bundled = requirements_in(out)
    assert "PyYAML==" in bundled
    assert "sphinx" not in bundled


def test_requirements_file_beside_a_package_is_ignored(tmp_path, shim_jar):
    pkg = tmp_path / "my_model"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    (pkg / "model.py").write_text(MODEL_WITH_DEPENDENCY)
    (tmp_path / "requirements.txt").write_text("sphinx\n")
    (pkg / "requirements.txt").write_text("twine\n")
    out = tmp_path / "out.jar"

    _package(f"{pkg / 'model.py'}:Mission", str(out))

    bundled = requirements_in(out)
    assert "PyYAML==" in bundled
    assert "sphinx" not in bundled
    assert "twine" not in bundled


def test_package_takes_no_requirements_argument():
    # The flag is gone; only --no-requirements remains. Guards against it creeping back
    # without the validation and cross-checking that used to accompany it.
    assert "requirements" not in inspect.signature(_package).parameters


# --- generated requirements ------------------------------------------------


def test_imports_are_generated_into_the_jar(tmp_path, shim_jar):
    model = tmp_path / "model.py"
    model.write_text(MODEL_WITH_DEPENDENCY)
    out = tmp_path / "out.jar"

    _package(f"{model}:Mission", str(out))

    bundled = requirements_in(out)
    assert "PyYAML==" in bundled
    assert bundled.startswith("# Generated by 'pymerlin package'")
    assert "Pymerlin-Requirements: pymerlin_requirements.txt" in manifest_of(out)


def test_generation_scans_every_file_of_a_package(tmp_path, shim_jar):
    pkg = tmp_path / "my_model"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    (pkg / "model.py").write_text(MODEL_SOURCE)
    (pkg / "helpers.py").write_text("import yaml\n")
    out = tmp_path / "out.jar"

    _package(f"{pkg / 'model.py'}:Mission", str(out))

    assert "PyYAML==" in requirements_in(out)


def test_package_internal_imports_are_not_generated(tmp_path, shim_jar):
    pkg = tmp_path / "my_model"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("")
    (pkg / "model.py").write_text("import helpers\nfrom my_model import helpers as h\n" + MODEL_SOURCE)
    (pkg / "helpers.py").write_text("")
    out = tmp_path / "out.jar"

    _package(f"{pkg / 'model.py'}:Mission", str(out))

    assert "pymerlin_requirements.txt" not in entries_of(out)


def test_single_file_model_importing_a_sibling_warns(tmp_path, shim_jar, capsys):
    # helpers.py sits next to the model but is not bundled — only a package ships whole.
    model = tmp_path / "model.py"
    model.write_text("import helpers\n" + MODEL_SOURCE)
    (tmp_path / "helpers.py").write_text("")
    out = tmp_path / "out.jar"

    _package(f"{model}:Mission", str(out))

    err = capsys.readouterr().err
    assert "imports helpers from its own directory" in err
    assert "__init__.py" in err
    # The sibling is a local module, so it must not have become a requirement.
    assert "pymerlin_requirements.txt" not in entries_of(out)


def test_model_needing_nothing_bundles_no_requirements(tmp_path, shim_jar, model_file):
    out = tmp_path / "out.jar"

    _package(f"{model_file}:Mission", str(out))

    assert "pymerlin_requirements.txt" not in entries_of(out)
    manifest = manifest_of(out)
    assert "Pymerlin-Requirements" not in manifest
    # The model ref is still the last attribute, and the manifest still ends blank-line
    # terminated as the JAR spec requires.
    assert manifest.endswith("Pymerlin-Model-Ref: pymerlin_models/model.py:Mission\r\n\r\n")


def test_no_requirements_flag_skips_generation(tmp_path, shim_jar):
    model = tmp_path / "model.py"
    model.write_text(MODEL_WITH_DEPENDENCY)
    out = tmp_path / "out.jar"

    _package(f"{model}:Mission", str(out), no_requirements=True)

    assert "pymerlin_requirements.txt" not in entries_of(out)


def test_manifest_keeps_model_ref_when_requirements_bundled(tmp_path, shim_jar):
    model = tmp_path / "model.py"
    model.write_text(MODEL_WITH_DEPENDENCY)
    out = tmp_path / "out.jar"

    _package(f"{model}:Mission", str(out))

    manifest = manifest_of(out)
    assert "Pymerlin-Model-Ref: pymerlin_models/model.py:Mission\r\n" in manifest
    assert manifest.endswith("\r\n\r\n")


def test_packaging_is_reproducible(tmp_path, shim_jar):
    # The generated file goes into the JAR, so it must not vary between identical runs.
    model = tmp_path / "model.py"
    model.write_text(MODEL_WITH_DEPENDENCY + "\nimport iniconfig\nimport pytest\n")

    first = tmp_path / "first.jar"
    second = tmp_path / "second.jar"
    _package(f"{model}:Mission", str(first))
    _package(f"{model}:Mission", str(second))

    assert requirements_in(first) == requirements_in(second)
