"""
Power Equipment List (PEL) component states.

Port of the ``missionmodel.power.pel.*_State`` enums.  In the Java model each of
these enums was generated by ``pel_java_generator.py`` from ``pel.json`` and
associates a Current-Best-Estimate (CBE) and Maximum-Expected-Value (MEV) power
load, in Watts, with each operational state of a spacecraft component.

Here every state is a Python ``Enum`` member whose value is the ``(cbe, mev)``
tuple; ``.cbe`` and ``.mev`` expose the two loads (mirroring ``getCBELoad`` /
``getMEVLoad`` in Java).
"""

from enum import Enum


class PELState(Enum):
    """Base class for a PEL component state carrying a (CBE, MEV) load in Watts."""

    def __init__(self, cbe: float, mev: float):
        self.cbe = cbe  # Current Best Estimate load (W)
        self.mev = mev  # Maximum Expected Value load (W)


class EPS_State(PELState):
    OFF = (0.0, 0.0)
    ON = (29.8, 29.8)
    SAFE = (32.8, 32.8)


class CDH_State(PELState):
    OFF = (0.0, 0.0)
    ON = (30.0, 30.0)


class SSR_State(PELState):
    OFF = (0.0, 0.0)
    ON = (19.2, 19.2)
    DOWNLINK = (21.4, 21.4)


class Heaters_State(PELState):
    SURVIVAL = (114.4, 114.4)
    DOWNLINK = (173.4, 173.4)
    RADAR_ON = (137.6, 137.6)


class ADCS_State(PELState):
    OFF = (0.0, 0.0)
    ON = (79.0, 79.0)
    TURNING = (187.0, 187.0)


class HarnessLoss_State(PELState):
    OFF = (0.0, 0.0)
    DOWNLINK = (38.4, 38.4)
    RADAR_ON = (38.2, 38.2)
    RADAR_OFF = (16.2, 16.2)
    TCM = (61.9, 61.9)


class Prop_State(PELState):
    OFF = (0.0, 0.0)
    DOWNLINK = (67.7, 67.7)
    TCM = (249.6, 249.6)


class IDST_State(PELState):
    OFF = (0.0, 0.0)
    ON = (16.0, 16.0)
    DOWNLINK = (22.0, 22.0)


class X_TWTA_State(PELState):
    OFF = (0.0, 0.0)
    ON = (173.4, 173.4)


class Ka_TWTA_State(PELState):
    OFF = (0.0, 0.0)
    ON = (135.4, 135.4)


class Radar_State(PELState):
    OFF = (0.0, 0.0)
    DOWNLINK = (198.2, 198.2)
    ON = (543.2, 543.2)


class Imager_State(PELState):
    OFF = (0.0, 0.0)
    ON = (13.0, 13.0)


class Radar_Heaters_State(PELState):
    OFF = (0.0, 0.0)
    CRUISE_SURVIVAL = (164.8, 164.8)
    SCIENCE_SURVIVAL = (9.5, 9.5)


class Imager_Heaters_State(PELState):
    OFF = (0.0, 0.0)
    CRUISE_SURVIVAL = (123.1, 123.1)
    IMAGER_ON = (92.4, 92.4)
    DOWNLINK = (14.0, 14.0)
    SCIENCE_SURVIVAL = (105.2, 105.2)
